/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AirlineManagementSystem;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author anusreemohanan
 */
public class PassengerJPanel extends javax.swing.JPanel {
    JPanel UserProcessContainer;
    /**
     * Creates new form PassengerJPanel
     */
    public PassengerJPanel() {
        initComponents();
    }

    PassengerJPanel(JPanel UserProcessContainer) {
        initComponents();
        this.UserProcessContainer = UserProcessContainer;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewPassenger = new javax.swing.JButton();
        btnUpdatePassenger = new javax.swing.JButton();
        btnAddPayment = new javax.swing.JButton();
        btnWithdrawPayment = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Passenger Panel");

        btnViewPassenger.setBackground(new java.awt.Color(153, 204, 255));
        btnViewPassenger.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnViewPassenger.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPassenger.setText("View Passenger Details");
        btnViewPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPassengerActionPerformed(evt);
            }
        });

        btnUpdatePassenger.setBackground(new java.awt.Color(153, 204, 255));
        btnUpdatePassenger.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnUpdatePassenger.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePassenger.setText("Update Passenger Details");
        btnUpdatePassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassengerActionPerformed(evt);
            }
        });

        btnAddPayment.setBackground(new java.awt.Color(153, 204, 255));
        btnAddPayment.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnAddPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPayment.setText("Add Payment");
        btnAddPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPaymentActionPerformed(evt);
            }
        });

        btnWithdrawPayment.setBackground(new java.awt.Color(153, 204, 255));
        btnWithdrawPayment.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnWithdrawPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnWithdrawPayment.setText("Withdraw Payment");
        btnWithdrawPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdatePassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWithdrawPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdatePassenger)
                    .addComponent(btnViewPassenger))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPayment)
                    .addComponent(btnWithdrawPayment))
                .addContainerGap(285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPassengerActionPerformed
        // TODO add your handling code here:
              ViewPassengerDetailsJPanel viewPanel = new ViewPassengerDetailsJPanel(UserProcessContainer);
              UserProcessContainer.add(viewPanel, "viewPanel");
              CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
              layout.show(UserProcessContainer, "viewPanel");
    }//GEN-LAST:event_btnViewPassengerActionPerformed

    private void btnAddPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPaymentActionPerformed
        // TODO add your handling code here:
        AddPaymentJPanel AddPaymentPanel = new AddPaymentJPanel(UserProcessContainer);
              UserProcessContainer.add(AddPaymentPanel, "AddPaymentPanel");
              CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
              layout.show(UserProcessContainer, "AddPaymentPanel");
    }//GEN-LAST:event_btnAddPaymentActionPerformed

    private void btnUpdatePassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassengerActionPerformed
        // TODO add your handling code here:
              UpdatePassengerDetailsJPanel updatePanel = new UpdatePassengerDetailsJPanel(UserProcessContainer);
              UserProcessContainer.add(updatePanel, "updatePanel");
              CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
              layout.show(UserProcessContainer, "updatePanel");
    }//GEN-LAST:event_btnUpdatePassengerActionPerformed

    private void btnWithdrawPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawPaymentActionPerformed
        // TODO add your handling code here:
              WithdrawPaymentJPanel deletePanel = new WithdrawPaymentJPanel(UserProcessContainer);
              UserProcessContainer.add(deletePanel, "deletePanel");
              CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
              layout.show(UserProcessContainer, "deletePanel");
    }//GEN-LAST:event_btnWithdrawPaymentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPayment;
    private javax.swing.JButton btnUpdatePassenger;
    private javax.swing.JButton btnViewPassenger;
    private javax.swing.JButton btnWithdrawPayment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
